<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
  <xsl:strip-space elements="*"/>
  <!-- Copy all attributes and nodes -->
  <xsl:template match="@*|node()">
    <xsl:message>Copying <xsl:value-of select="name()"/></xsl:message>
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="/">
    <xsl:comment>
      <xsl:text>&#xa;</xsl:text>
      <xsl:text>Generated by </xsl:text>
      <xsl:value-of select="system-property('xsl:product-name')"/>
      <xsl:text> </xsl:text>
      <xsl:value-of select="system-property('xsl:product-version')"/>
      <xsl:text>&#xa;</xsl:text>
    </xsl:comment>
    <xsl:apply-templates select="node()"/>
  </xsl:template>
</xsl:stylesheet>
